#msg22xx touchpanel driver


obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_qcom.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_common.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_utility_adaption.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_self_fw_control.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_self_mp_test.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_ic_fw_porting_layer.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_main.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_platform_interface.o

obj-$(CONFIG_TOUCHSCREEN_MSG22XX)	+= mstar_drv_platform_porting_layer.o
